FROM php:8-fpm AS standard-phpfpm

RUN apt-get update && apt-get upgrade -y  && apt-get install -y  ca-certificates curl git npm unzip zip

COPY --from=mlocati/php-extension-installer /usr/bin/install-php-extensions /usr/local/bin/

# install desired php extensions
RUN install-php-extensions gd pdo_mysql bcmath zip intl opcache mysqli


COPY --from=composer:2.0 /usr/bin/composer /usr/local/bin/composer
