version: "3.1"
networks:
  backend:
    driver: bridge
volumes:
  wordpress:
  # wp3-volume:
services:
  # variables are located in .env in this directory
  node:
    build: 
      context: "./docker/node/"
      args:
          EXPOSE_PORT: ${EXPOSE_PORT}
    environment:
      ENV_EXPOSE_PORT: ${EXPOSE_PORT}
    ports: 
      - "${EXPOSE_PORT}:${EXPOSE_PORT}"
    volumes:
      - ./src/vite-app:/app

  # standalone instance of the ride-pooling plugin
  wp:
    # image: wordpress
    build: ./docker/wordpress/
    restart: always
    ports:
      - ${WP_PORT}:80
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: ${DB_ROOT_PASSWORD}
      WORDPRESS_DB_NAME: "${DB_NAME}"
    volumes:
      - wordpress:/var/www/html
    logging:
      options:
        max-size: 2m
    depends_on:
      - db
    networks:
      - backend

  # wp-client for wp1 container
  wpcli:
    # image: wordpress:cli
    build: ./docker/wpcli/
    volumes:
      - ./config/php.conf.ini:/usr/local/etc/php/conf.d/conf.ini
      - wordpress:/var/www/html
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: ${DB_ROOT_PASSWORD}
      WORDPRESS_DB_NAME: "${DB_NAME}"
      WP1_SLUG: "${WP1_SLUG}" 
      WP1_TITLE: "${WP1_TITLE}" 
      WP2_SLUG: "${WP2_SLUG}" 
      WP2_TITLE: "${WP2_TITLE}" 
      WP3_SLUG: "${WP3_SLUG}" 
      WP3_TITLE: "${WP3_TITLE}" 
      WP4_SLUG: "${WP4_SLUG}" 
      WP4_TITLE: "${WP4_TITLE}"
    depends_on:
      - db
      - wp
    links:
      - db
    networks:
      - backend
    user: xfs
    command: >
      /bin/sh -c '
      sleep 10;
      wp core multisite-install --path="/var/www/html" --url="http://localhost:${WP_PORT}" --title="${WP_MAIN_TITLE}" --admin_user=admin --admin_password=${WP_ADMIN_PASS} --admin_email=${WP_EMAIL};
      wp --require=/tmp/wp-multisite-setup.php multisite install
      '

  # mysql container for all wp containers
  db:
    image: mysql:5.7
    # build: ./docker/mysql/
    restart: always
    environment:
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
    command:
      [
        '--default_authentication_plugin=mysql_native_password',
        '--character-set-server=utf8mb4',
        '--collation-server=utf8mb4_unicode_ci'
      ]
    volumes:
      - ./db/:/var/lib/mysql
      # - ./docker/mysql/database-setup.sh:/docker-entrypoint-initdb.d/database-setup.sh
    networks:
      - backend

  # database management
  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 8389:80
    environment:
      - PMA_ARBITRARY=1
      - UPLOAD_LIMIT=128M
    networks:
      - backend
