#!/bin/bash
echo ${APP_MYSQL_DATABASE} und ${APP_MYSQL_USER} und ${APP_MYSQL_PASSWORD}
mysql -u root --password=${MYSQL_ROOT_PASSWORD}   << EOF
CREATE DATABASE ${APP_MYSQL_DATABASE}1 CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
CREATE DATABASE ${APP_MYSQL_DATABASE}2 CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
-- CREATE DATABASE ${APP_MYSQL_DATABASE}3 CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
GRANT SELECT, INSERT, UPDATE, DELETE, CREATE, DROP, INDEX, ALTER, CREATE TEMPORARY TABLES, CREATE VIEW, EVENT, TRIGGER, SHOW VIEW, CREATE ROUTINE, ALTER ROUTINE, EXECUTE ON ${APP_MYSQL_DATABASE}1.* TO '${APP_MYSQL_USER}'@'%';
GRANT SELECT, INSERT, UPDATE, DELETE, CREATE, DROP, INDEX, ALTER, CREATE TEMPORARY TABLES, CREATE VIEW, EVENT, TRIGGER, SHOW VIEW, CREATE ROUTINE, ALTER ROUTINE, EXECUTE ON ${APP_MYSQL_DATABASE}2.* TO '${APP_MYSQL_USER}'@'%';
-- GRANT SELECT, INSERT, UPDATE, DELETE, CREATE, DROP, INDEX, ALTER, CREATE TEMPORARY TABLES, CREATE VIEW, EVENT, TRIGGER, SHOW VIEW, CREATE ROUTINE, ALTER ROUTINE, EXECUTE ON ${APP_MYSQL_DATABASE}3.* TO '${APP_MYSQL_USER}'@'%';
EOF
